// Generated by gencpp from file wrock/cube_kin.msg
// DO NOT EDIT!


#ifndef WROCK_MESSAGE_CUBE_KIN_H
#define WROCK_MESSAGE_CUBE_KIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wrock
{
template <class ContainerAllocator>
struct cube_kin_
{
  typedef cube_kin_<ContainerAllocator> Type;

  cube_kin_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  cube_kin_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::wrock::cube_kin_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wrock::cube_kin_<ContainerAllocator> const> ConstPtr;

}; // struct cube_kin_

typedef ::wrock::cube_kin_<std::allocator<void> > cube_kin;

typedef boost::shared_ptr< ::wrock::cube_kin > cube_kinPtr;
typedef boost::shared_ptr< ::wrock::cube_kin const> cube_kinConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wrock::cube_kin_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wrock::cube_kin_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wrock

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'wrock': ['/home/mike/catkin_ws/src/wrock/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wrock::cube_kin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wrock::cube_kin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wrock::cube_kin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wrock::cube_kin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wrock::cube_kin_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wrock::cube_kin_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wrock::cube_kin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0d3dd786c2f8b53c20fdbbc0542c544";
  }

  static const char* value(const ::wrock::cube_kin_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0d3dd786c2f8b53ULL;
  static const uint64_t static_value2 = 0xc20fdbbc0542c544ULL;
};

template<class ContainerAllocator>
struct DataType< ::wrock::cube_kin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wrock/cube_kin";
  }

  static const char* value(const ::wrock::cube_kin_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wrock::cube_kin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 pitch\n\
float32 yaw\n\
\n\
";
  }

  static const char* value(const ::wrock::cube_kin_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wrock::cube_kin_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cube_kin_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wrock::cube_kin_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wrock::cube_kin_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WROCK_MESSAGE_CUBE_KIN_H
