scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.05
    upper_threshold: .inf
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.4
    upper_angle: 1.57
- name: intensity
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 0
    upper_threshold: 3000
    disp_histogram: 0
