(cl:defpackage phd-srv
  (:use )
  (:export
   "THICKNESS_SERVICE"
   "<THICKNESS_SERVICE-REQUEST>"
   "THICKNESS_SERVICE-REQUEST"
   "<THICKNESS_SERVICE-RESPONSE>"
   "THICKNESS_SERVICE-RESPONSE"
   "LOCALIZE_CLOUD"
   "<LOCALIZE_CLOUD-REQUEST>"
   "LOCALIZE_CLOUD-REQUEST"
   "<LOCALIZE_CLOUD-RESPONSE>"
   "LOCALIZE_CLOUD-RESPONSE"
   "TRAJECTORY_SERVICE (NONLINEAR)"
   "<TRAJECTORY_SERVICE (NONLINEAR)-REQUEST>"
   "TRAJECTORY_SERVICE (NONLINEAR)-REQUEST"
   "<TRAJECTORY_SERVICE (NONLINEAR)-RESPONSE>"
   "TRAJECTORY_SERVICE (NONLINEAR)-RESPONSE"
   "TRAJECTORY_SERVICE"
   "<TRAJECTORY_SERVICE-REQUEST>"
   "TRAJECTORY_SERVICE-REQUEST"
   "<TRAJECTORY_SERVICE-RESPONSE>"
   "TRAJECTORY_SERVICE-RESPONSE"
  ))

