//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the registration_localization package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __registration_localization__SEGCONFIG_H__
#define __registration_localization__SEGCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace registration_localization
{
  class SEGConfigStatics;
  
  class SEGConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(SEGConfig &config, const SEGConfig &max, const SEGConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const SEGConfig &config1, const SEGConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, SEGConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const SEGConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SEGConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const SEGConfig &config) const = 0;
      virtual void getValue(const SEGConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T SEGConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (SEGConfig::* field);

      virtual void clamp(SEGConfig &config, const SEGConfig &max, const SEGConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const SEGConfig &config1, const SEGConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, SEGConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const SEGConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SEGConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const SEGConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const SEGConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, SEGConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, SEGConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<SEGConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(SEGConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("k_search"==(*_i)->name){k_search = boost::any_cast<int>(val);}
        if("max_iterations"==(*_i)->name){max_iterations = boost::any_cast<int>(val);}
        if("radius_search"==(*_i)->name){radius_search = boost::any_cast<double>(val);}
        if("distance_threshold"==(*_i)->name){distance_threshold = boost::any_cast<double>(val);}
        if("normal_distance_weight"==(*_i)->name){normal_distance_weight = boost::any_cast<double>(val);}
        if("eps_angle"==(*_i)->name){eps_angle = boost::any_cast<double>(val);}
        if("leaf_size"==(*_i)->name){leaf_size = boost::any_cast<double>(val);}
        if("minmax"==(*_i)->name){minmax = boost::any_cast<double>(val);}
        if("minmin"==(*_i)->name){minmin = boost::any_cast<double>(val);}
        if("model_type"==(*_i)->name){model_type = boost::any_cast<double>(val);}
        if("optimize_coefficients"==(*_i)->name){optimize_coefficients = boost::any_cast<bool>(val);}
        if("skip_downsample"==(*_i)->name){skip_downsample = boost::any_cast<bool>(val);}
        if("distance_threshold2"==(*_i)->name){distance_threshold2 = boost::any_cast<double>(val);}
        if("normal_distance_weight2"==(*_i)->name){normal_distance_weight2 = boost::any_cast<double>(val);}
        if("optimize_coefficients2"==(*_i)->name){optimize_coefficients2 = boost::any_cast<bool>(val);}
        if("dot_product"==(*_i)->name){dot_product = boost::any_cast<double>(val);}
        if("dot_product_accuracy"==(*_i)->name){dot_product_accuracy = boost::any_cast<double>(val);}
        if("purpendicularity_accuracy"==(*_i)->name){purpendicularity_accuracy = boost::any_cast<double>(val);}
      }
    }

    int k_search;
int max_iterations;
double radius_search;
double distance_threshold;
double normal_distance_weight;
double eps_angle;
double leaf_size;
double minmax;
double minmin;
double model_type;
bool optimize_coefficients;
bool skip_downsample;
double distance_threshold2;
double normal_distance_weight2;
bool optimize_coefficients2;
double dot_product;
double dot_product_accuracy;
double purpendicularity_accuracy;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int k_search;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_iterations;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double radius_search;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distance_threshold;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_distance_weight;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double eps_angle;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double leaf_size;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double minmax;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double minmin;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double model_type;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool optimize_coefficients;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool skip_downsample;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distance_threshold2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_distance_weight2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool optimize_coefficients2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dot_product;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dot_product_accuracy;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double purpendicularity_accuracy;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("SEGConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const SEGConfig &__max__ = __getMax__();
      const SEGConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const SEGConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const SEGConfig &__getDefault__();
    static const SEGConfig &__getMax__();
    static const SEGConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const SEGConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void SEGConfig::ParamDescription<std::string>::clamp(SEGConfig &config, const SEGConfig &max, const SEGConfig &min) const
  {
    return;
  }

  class SEGConfigStatics
  {
    friend class SEGConfig;
    
    SEGConfigStatics()
    {
SEGConfig::GroupDescription<SEGConfig::DEFAULT, SEGConfig> Default("Default", "", 0, 0, true, &SEGConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_search = -2147483648;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_search = 2147483647;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_search = 30;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<int>("k_search", "int", 0, "An Integer parameter", "", &SEGConfig::k_search)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<int>("k_search", "int", 0, "An Integer parameter", "", &SEGConfig::k_search)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_iterations = -2147483648;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_iterations = 2147483647;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_iterations = 1000;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<int>("max_iterations", "int", 0, "An Integer parameter", "", &SEGConfig::max_iterations)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<int>("max_iterations", "int", 0, "An Integer parameter", "", &SEGConfig::max_iterations)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.radius_search = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.radius_search = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.radius_search = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("radius_search", "double", 0, "A double parameter", "", &SEGConfig::radius_search)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("radius_search", "double", 0, "A double parameter", "", &SEGConfig::radius_search)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distance_threshold = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distance_threshold = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distance_threshold = 0.15;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("distance_threshold", "double", 0, "A double parameter", "", &SEGConfig::distance_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("distance_threshold", "double", 0, "A double parameter", "", &SEGConfig::distance_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_distance_weight = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_distance_weight = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_distance_weight = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("normal_distance_weight", "double", 0, "A double parameter", "", &SEGConfig::normal_distance_weight)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("normal_distance_weight", "double", 0, "A double parameter", "", &SEGConfig::normal_distance_weight)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.eps_angle = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.eps_angle = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.eps_angle = 0.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("eps_angle", "double", 0, "A double parameter", "", &SEGConfig::eps_angle)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("eps_angle", "double", 0, "A double parameter", "", &SEGConfig::eps_angle)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.leaf_size = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.leaf_size = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.leaf_size = 0.02;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("leaf_size", "double", 0, "A double parameter", "", &SEGConfig::leaf_size)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("leaf_size", "double", 0, "A double parameter", "", &SEGConfig::leaf_size)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minmax = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minmax = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minmax = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("minmax", "double", 0, "A double parameter", "", &SEGConfig::minmax)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("minmax", "double", 0, "A double parameter", "", &SEGConfig::minmax)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minmin = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minmin = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minmin = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("minmin", "double", 0, "A double parameter", "", &SEGConfig::minmin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("minmin", "double", 0, "A double parameter", "", &SEGConfig::minmin)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.model_type = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.model_type = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.model_type = 17.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("model_type", "double", 0, "A double parameter", "", &SEGConfig::model_type)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("model_type", "double", 0, "A double parameter", "", &SEGConfig::model_type)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.optimize_coefficients = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.optimize_coefficients = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.optimize_coefficients = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("optimize_coefficients", "bool", 0, "A Boolean parameter", "", &SEGConfig::optimize_coefficients)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("optimize_coefficients", "bool", 0, "A Boolean parameter", "", &SEGConfig::optimize_coefficients)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.skip_downsample = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.skip_downsample = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.skip_downsample = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("skip_downsample", "bool", 0, "A Boolean parameter", "", &SEGConfig::skip_downsample)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("skip_downsample", "bool", 0, "A Boolean parameter", "", &SEGConfig::skip_downsample)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distance_threshold2 = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distance_threshold2 = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distance_threshold2 = 0.02;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("distance_threshold2", "double", 0, "A double parameter", "", &SEGConfig::distance_threshold2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("distance_threshold2", "double", 0, "A double parameter", "", &SEGConfig::distance_threshold2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_distance_weight2 = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_distance_weight2 = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_distance_weight2 = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("normal_distance_weight2", "double", 0, "A double parameter", "", &SEGConfig::normal_distance_weight2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("normal_distance_weight2", "double", 0, "A double parameter", "", &SEGConfig::normal_distance_weight2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.optimize_coefficients2 = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.optimize_coefficients2 = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.optimize_coefficients2 = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("optimize_coefficients2", "bool", 0, "A Boolean parameter", "", &SEGConfig::optimize_coefficients2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<bool>("optimize_coefficients2", "bool", 0, "A Boolean parameter", "", &SEGConfig::optimize_coefficients2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dot_product = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dot_product = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dot_product = 0.4567;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("dot_product", "double", 0, "A double parameter", "", &SEGConfig::dot_product)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("dot_product", "double", 0, "A double parameter", "", &SEGConfig::dot_product)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dot_product_accuracy = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dot_product_accuracy = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dot_product_accuracy = 0.02;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("dot_product_accuracy", "double", 0, "A double parameter", "", &SEGConfig::dot_product_accuracy)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("dot_product_accuracy", "double", 0, "A double parameter", "", &SEGConfig::dot_product_accuracy)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.purpendicularity_accuracy = -std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.purpendicularity_accuracy = std::numeric_limits<double>::infinity();
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.purpendicularity_accuracy = 0.15;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("purpendicularity_accuracy", "double", 0, "A double parameter", "", &SEGConfig::purpendicularity_accuracy)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SEGConfig::AbstractParamDescriptionConstPtr(new SEGConfig::ParamDescription<double>("purpendicularity_accuracy", "double", 0, "A double parameter", "", &SEGConfig::purpendicularity_accuracy)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(SEGConfig::AbstractGroupDescriptionConstPtr(new SEGConfig::GroupDescription<SEGConfig::DEFAULT, SEGConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<SEGConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<SEGConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<SEGConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    SEGConfig __max__;
    SEGConfig __min__;
    SEGConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const SEGConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static SEGConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &SEGConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const SEGConfig &SEGConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const SEGConfig &SEGConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const SEGConfig &SEGConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<SEGConfig::AbstractParamDescriptionConstPtr> &SEGConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<SEGConfig::AbstractGroupDescriptionConstPtr> &SEGConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const SEGConfigStatics *SEGConfig::__get_statics__()
  {
    const static SEGConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = SEGConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __SEGRECONFIGURATOR_H__
