set(_CATKIN_CURRENT_PACKAGE "wrock")
set(wrock_VERSION "0.0.0")
set(wrock_MAINTAINER "mike <mike@todo.todo>")
set(wrock_PACKAGE_FORMAT "1")
set(wrock_BUILD_DEPENDS "rospy" "sensor_msgs" "urdf" "diagnostic_updater" "schunk_libm5api" "libntcan" "libpcan" "cob_srvs" "brics_actuator" "diagnostic_msgs" "control_msgs" "rostest" "tf" "message_generation" "libpcl-all-dev" "roscpp" "libpcan" "husky_description" "pluginlib" "rviz")
set(wrock_BUILD_EXPORT_DEPENDS "husky_description" "libpcan" "roscpp" "libpcl-all" "message_runtime" "tf" "sensor_msgs" "urdf" "diagnostic_updater" "schunk_libm5api" "libntcan" "libpcan" "cob_srvs" "brics_actuator" "diagnostic_msgs" "control_msgs" "pluginlib" "rviz")
set(wrock_BUILDTOOL_DEPENDS "catkin")
set(wrock_BUILDTOOL_EXPORT_DEPENDS )
set(wrock_EXEC_DEPENDS "husky_description" "libpcan" "roscpp" "libpcl-all" "message_runtime" "tf" "sensor_msgs" "urdf" "diagnostic_updater" "schunk_libm5api" "libntcan" "libpcan" "cob_srvs" "brics_actuator" "diagnostic_msgs" "control_msgs" "pluginlib" "rviz")
set(wrock_RUN_DEPENDS "husky_description" "libpcan" "roscpp" "libpcl-all" "message_runtime" "tf" "sensor_msgs" "urdf" "diagnostic_updater" "schunk_libm5api" "libntcan" "cob_srvs" "brics_actuator" "diagnostic_msgs" "control_msgs" "pluginlib" "rviz")
set(wrock_TEST_DEPENDS )
set(wrock_DOC_DEPENDS )
set(wrock_DEPRECATED "")