// Generated by gencpp from file phd/accuracy_service.msg
// DO NOT EDIT!


#ifndef PHD_MESSAGE_ACCURACY_SERVICE_H
#define PHD_MESSAGE_ACCURACY_SERVICE_H

#include <ros/service_traits.h>


#include <phd/accuracy_serviceRequest.h>
#include <phd/accuracy_serviceResponse.h>


namespace phd
{

struct accuracy_service
{

typedef accuracy_serviceRequest Request;
typedef accuracy_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct accuracy_service
} // namespace phd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phd::accuracy_service > {
  static const char* value()
  {
    return "d6902a0a52e4f694a57d510cce74d5d2";
  }

  static const char* value(const ::phd::accuracy_service&) { return value(); }
};

template<>
struct DataType< ::phd::accuracy_service > {
  static const char* value()
  {
    return "phd/accuracy_service";
  }

  static const char* value(const ::phd::accuracy_service&) { return value(); }
};


// service_traits::MD5Sum< ::phd::accuracy_serviceRequest> should match 
// service_traits::MD5Sum< ::phd::accuracy_service > 
template<>
struct MD5Sum< ::phd::accuracy_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phd::accuracy_service >::value();
  }
  static const char* value(const ::phd::accuracy_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::accuracy_serviceRequest> should match 
// service_traits::DataType< ::phd::accuracy_service > 
template<>
struct DataType< ::phd::accuracy_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::phd::accuracy_service >::value();
  }
  static const char* value(const ::phd::accuracy_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phd::accuracy_serviceResponse> should match 
// service_traits::MD5Sum< ::phd::accuracy_service > 
template<>
struct MD5Sum< ::phd::accuracy_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phd::accuracy_service >::value();
  }
  static const char* value(const ::phd::accuracy_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::accuracy_serviceResponse> should match 
// service_traits::DataType< ::phd::accuracy_service > 
template<>
struct DataType< ::phd::accuracy_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::phd::accuracy_service >::value();
  }
  static const char* value(const ::phd::accuracy_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHD_MESSAGE_ACCURACY_SERVICE_H
