// Generated by gencpp from file phd/calc_service.msg
// DO NOT EDIT!


#ifndef PHD_MESSAGE_CALC_SERVICE_H
#define PHD_MESSAGE_CALC_SERVICE_H

#include <ros/service_traits.h>


#include <phd/calc_serviceRequest.h>
#include <phd/calc_serviceResponse.h>


namespace phd
{

struct calc_service
{

typedef calc_serviceRequest Request;
typedef calc_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calc_service
} // namespace phd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phd::calc_service > {
  static const char* value()
  {
    return "3e940f6cd215fa9d81d97d506548ddde";
  }

  static const char* value(const ::phd::calc_service&) { return value(); }
};

template<>
struct DataType< ::phd::calc_service > {
  static const char* value()
  {
    return "phd/calc_service";
  }

  static const char* value(const ::phd::calc_service&) { return value(); }
};


// service_traits::MD5Sum< ::phd::calc_serviceRequest> should match 
// service_traits::MD5Sum< ::phd::calc_service > 
template<>
struct MD5Sum< ::phd::calc_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phd::calc_service >::value();
  }
  static const char* value(const ::phd::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::calc_serviceRequest> should match 
// service_traits::DataType< ::phd::calc_service > 
template<>
struct DataType< ::phd::calc_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::phd::calc_service >::value();
  }
  static const char* value(const ::phd::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phd::calc_serviceResponse> should match 
// service_traits::MD5Sum< ::phd::calc_service > 
template<>
struct MD5Sum< ::phd::calc_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phd::calc_service >::value();
  }
  static const char* value(const ::phd::calc_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::calc_serviceResponse> should match 
// service_traits::DataType< ::phd::calc_service > 
template<>
struct DataType< ::phd::calc_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::phd::calc_service >::value();
  }
  static const char* value(const ::phd::calc_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHD_MESSAGE_CALC_SERVICE_H
