// Generated by gencpp from file phd/doctor_cloud.msg
// DO NOT EDIT!


#ifndef PHD_MESSAGE_DOCTOR_CLOUD_H
#define PHD_MESSAGE_DOCTOR_CLOUD_H

#include <ros/service_traits.h>


#include <phd/doctor_cloudRequest.h>
#include <phd/doctor_cloudResponse.h>


namespace phd
{

struct doctor_cloud
{

typedef doctor_cloudRequest Request;
typedef doctor_cloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct doctor_cloud
} // namespace phd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phd::doctor_cloud > {
  static const char* value()
  {
    return "cae4fb365d52ae353fa3450fdf68bef2";
  }

  static const char* value(const ::phd::doctor_cloud&) { return value(); }
};

template<>
struct DataType< ::phd::doctor_cloud > {
  static const char* value()
  {
    return "phd/doctor_cloud";
  }

  static const char* value(const ::phd::doctor_cloud&) { return value(); }
};


// service_traits::MD5Sum< ::phd::doctor_cloudRequest> should match 
// service_traits::MD5Sum< ::phd::doctor_cloud > 
template<>
struct MD5Sum< ::phd::doctor_cloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phd::doctor_cloud >::value();
  }
  static const char* value(const ::phd::doctor_cloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::doctor_cloudRequest> should match 
// service_traits::DataType< ::phd::doctor_cloud > 
template<>
struct DataType< ::phd::doctor_cloudRequest>
{
  static const char* value()
  {
    return DataType< ::phd::doctor_cloud >::value();
  }
  static const char* value(const ::phd::doctor_cloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phd::doctor_cloudResponse> should match 
// service_traits::MD5Sum< ::phd::doctor_cloud > 
template<>
struct MD5Sum< ::phd::doctor_cloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phd::doctor_cloud >::value();
  }
  static const char* value(const ::phd::doctor_cloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::doctor_cloudResponse> should match 
// service_traits::DataType< ::phd::doctor_cloud > 
template<>
struct DataType< ::phd::doctor_cloudResponse>
{
  static const char* value()
  {
    return DataType< ::phd::doctor_cloud >::value();
  }
  static const char* value(const ::phd::doctor_cloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHD_MESSAGE_DOCTOR_CLOUD_H
