// Generated by gencpp from file phd/empty.msg
// DO NOT EDIT!


#ifndef PHD_MESSAGE_EMPTY_H
#define PHD_MESSAGE_EMPTY_H

#include <ros/service_traits.h>


#include <phd/emptyRequest.h>
#include <phd/emptyResponse.h>


namespace phd
{

struct empty
{

typedef emptyRequest Request;
typedef emptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct empty
} // namespace phd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phd::empty > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::phd::empty&) { return value(); }
};

template<>
struct DataType< ::phd::empty > {
  static const char* value()
  {
    return "phd/empty";
  }

  static const char* value(const ::phd::empty&) { return value(); }
};


// service_traits::MD5Sum< ::phd::emptyRequest> should match 
// service_traits::MD5Sum< ::phd::empty > 
template<>
struct MD5Sum< ::phd::emptyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phd::empty >::value();
  }
  static const char* value(const ::phd::emptyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::emptyRequest> should match 
// service_traits::DataType< ::phd::empty > 
template<>
struct DataType< ::phd::emptyRequest>
{
  static const char* value()
  {
    return DataType< ::phd::empty >::value();
  }
  static const char* value(const ::phd::emptyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phd::emptyResponse> should match 
// service_traits::MD5Sum< ::phd::empty > 
template<>
struct MD5Sum< ::phd::emptyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phd::empty >::value();
  }
  static const char* value(const ::phd::emptyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::emptyResponse> should match 
// service_traits::DataType< ::phd::empty > 
template<>
struct DataType< ::phd::emptyResponse>
{
  static const char* value()
  {
    return DataType< ::phd::empty >::value();
  }
  static const char* value(const ::phd::emptyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHD_MESSAGE_EMPTY_H
