// Generated by gencpp from file phd/thickness_service.msg
// DO NOT EDIT!


#ifndef PHD_MESSAGE_THICKNESS_SERVICE_H
#define PHD_MESSAGE_THICKNESS_SERVICE_H

#include <ros/service_traits.h>


#include <phd/thickness_serviceRequest.h>
#include <phd/thickness_serviceResponse.h>


namespace phd
{

struct thickness_service
{

typedef thickness_serviceRequest Request;
typedef thickness_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct thickness_service
} // namespace phd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phd::thickness_service > {
  static const char* value()
  {
    return "0fa11251ff61f1cb78f9a7e04b6af3f2";
  }

  static const char* value(const ::phd::thickness_service&) { return value(); }
};

template<>
struct DataType< ::phd::thickness_service > {
  static const char* value()
  {
    return "phd/thickness_service";
  }

  static const char* value(const ::phd::thickness_service&) { return value(); }
};


// service_traits::MD5Sum< ::phd::thickness_serviceRequest> should match 
// service_traits::MD5Sum< ::phd::thickness_service > 
template<>
struct MD5Sum< ::phd::thickness_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phd::thickness_service >::value();
  }
  static const char* value(const ::phd::thickness_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::thickness_serviceRequest> should match 
// service_traits::DataType< ::phd::thickness_service > 
template<>
struct DataType< ::phd::thickness_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::phd::thickness_service >::value();
  }
  static const char* value(const ::phd::thickness_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phd::thickness_serviceResponse> should match 
// service_traits::MD5Sum< ::phd::thickness_service > 
template<>
struct MD5Sum< ::phd::thickness_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phd::thickness_service >::value();
  }
  static const char* value(const ::phd::thickness_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phd::thickness_serviceResponse> should match 
// service_traits::DataType< ::phd::thickness_service > 
template<>
struct DataType< ::phd::thickness_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::phd::thickness_service >::value();
  }
  static const char* value(const ::phd::thickness_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHD_MESSAGE_THICKNESS_SERVICE_H
